[deploy]
bucket = 'cfn-artifacts-ohary37.com'
region = 'us-east-1'
stack_name = 'CrudDb'
master_password = 'cruddurroot'

[parameters]
NetworkingStack = 'CrudNet'
ClusterStack = 'CrudCluster'
MasterUsername = 'cruddurroot'