[deploy]
bucket = 'cfn-artifacts-ohary37.com'
region = 'us-east-1'
stack_name = 'CrudCicd'

[parameters]
ServiceStack = 'CrudSrvBackendFlask'
ClusterStack = 'CrudCluster'
GitHubBranch = 'prod'
GithubRepo = 'HillaryUgwu/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-cruddur-artifacts-ohary37.com"