[deploy]
stack_name = 'CrudCognito'

[parameters]
NetworkingStack = 'CrudNet'
CrudDBStack = 'CrudDb'
UserPoolName = 'Cruddur-user-pool'
ClientName = 'Cruddur'
LambdaFunctionName = 'cruddur-post-confirmation-lambda'